# Generated by Django 4.2.2 on 2023-09-26 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('localidad', models.CharField(max_length=14)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=8)),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=14)),
                ('localidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=True, max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.SmallIntegerField()),
                ('fecha_pedido', models.DateField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestion.cliente')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=8)),
                ('oficio', models.CharField(max_length=10)),
                ('fecha_alta', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=8)),
                ('telefono', models.CharField(max_length=14)),
                ('dep_id', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='appGestion.departamento')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGestion.empleado')),
            ],
        ),
    ]
