# Generated by Django 4.2.2 on 2023-09-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion', '0002_subscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscripcion',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
