# Generated by Django 4.2.2 on 2023-09-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion', '0002_cliente_departamento_subscripcion_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='dep_id',
            new_name='dep',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='director',
        ),
    ]
