# Generated by Django 4.2.2 on 2023-09-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion', '0003_alter_subscripcion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscripcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
