# Generated by Django 4.2.2 on 2023-09-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion', '0003_rename_dep_id_empleado_dep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscripcion',
            name='fecha_alta',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(auto_now=True),
        ),
    ]
