# Generated by Django 4.2.2 on 2023-09-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestion', '0005_subscripcion_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('localidad', models.CharField(max_length=14)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=8)),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('dep_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('dnombre', models.CharField(max_length=14)),
                ('localidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('unidades', models.SmallIntegerField()),
                ('fecha_pedido', models.DateField()),
                ('cliente_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestion.cliente')),
                ('producto_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emp_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=8)),
                ('oficio', models.CharField(max_length=10)),
                ('fecha_alta', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=8)),
                ('telefono', models.CharField(max_length=14)),
                ('dep_no', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='appGestion.departamento')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGestion.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor_no',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appGestion.empleado'),
        ),
    ]
